import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Rubik } from "next/font/google";
import "@/app/globals.css"
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
const rubik = Rubik({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${rubik.className} h-full`}>
      <body className="flex flex-col relative min-h-screen font-sans">
      <div className="absolute inset-0 bg-[#08080a] -z-11"/>
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#0d0d0f_1px,transparent_1px),linear-gradient(to_bottom,#0d0d0f_1px,transparent_1px)] bg-size-[3rem_3rem] -z-10 bg-repeat"/>
      {children}</body>
    </html>
  );
}
